# Generated by Django 3.0.3 on 2020-12-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria  ',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
