# Generated by Django 3.0.3 on 2021-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Nombre_categoria',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoria'),
        ),
    ]
