# Generated by Django 3.0.3 on 2021-01-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20210112_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='público',
        ),
        migrations.AlterField(
            model_name='documento',
            name='Privado',
            field=models.BooleanField(default=False, help_text='El documento es oculto para los usuarios ', verbose_name='Privado'),
        ),
    ]
