# Generated by Django 3.0.3 on 2021-01-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_auto_20210113_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Descargas',
            field=models.BooleanField(default=False),
        ),
    ]
